/* Generated By:JJTree: Do not edit this line. ASTdotted_name.java */

package uchicago.src.sim.parameter.rpl;

public class ASTdotted_name extends SimpleNode {
  public ASTdotted_name(int id) {
    super(id);
  }

  public ASTdotted_name(RPLParser p, int id) {
    super(p, id);
  }

  public RPLObject getValue() {
    // two children of dotted name are ASTName
    RPLDottedName rn = new RPLDottedName((String)children[0].getInfo(),
                             (String)children[1].getInfo());
    rn.setLineCol(this.beginLine, this.beginColumn);
    return rn;
  }

}
