/* Generated By:JJTree: Do not edit this line. ASTFloat.java */

package uchicago.src.sim.parameter.rpl;

public class ASTFloat extends SimpleNode {
  public ASTFloat(int id) {
    super(id);
  }

  public ASTFloat(RPLParser p, int id) {
    super(p, id);
  }

  public RPLObject getValue() {
    Number n = (Number)info;
    if (info instanceof Double) return new RPLDoubleValue(n.doubleValue());
    return new RPLFloatValue(n.floatValue());
  }

}
