/* Generated By:JJTree: Do not edit this line. ASTInt.java */

package uchicago.src.sim.parameter.rpl;

public class ASTInt extends SimpleNode {
  
  public ASTInt(int id) {
    super(id);
  }

  public ASTInt(RPLParser p, int id) {
    super(p, id);
  }

  public RPLObject getValue() {
    Number n = (Number)info;
    if (info instanceof Long) return new RPLLongValue(n.longValue());
    return new RPLIntValue(n.intValue());
  }

}
