/* Generated By:JJTree: Do not edit this line. ASTlist_assign.java */

package uchicago.src.sim.parameter.rpl;

public class ASTlist_assign extends SimpleNode {

  String varName;

  public ASTlist_assign(int id) {
    super(id);
  }

  public ASTlist_assign(RPLParser p, int id) {
    super(p, id);
  }

  public void preProcess(RPLCompiler compiler) {
    // first child is an ASTName
    varName = children[0].getInfo().toString();
    // second child is an ASTList
    children[1].preProcess(compiler);
  }

  public void compile(RPLCompiler compiler) {
    ASTlist list = (ASTlist)children[1];
    list.compile(compiler);
    if (compiler.hasGlobalVariable(varName)) {
      String message = "variable '" + varName + "' is already defined.";
      throw compiler.createCompilerException(message, this.beginLine);
    }
    compiler.addGlobalVar(varName, list.getRPLList());

    //System.out.println(varName + " = " + list.getRPLList());
  }
}
