/* Generated By:JJTree: Do not edit this line. ASTName.java */

package uchicago.src.sim.parameter.rpl;

public class ASTName extends SimpleNode {
  public ASTName(int id) {
    super(id);
  }

  public ASTName(RPLParser p, int id) {
    super(p, id);
  }
}
