/* Generated By:JJTree: Do not edit this line. ASTString.java */

package uchicago.src.sim.parameter.rpl;

public class ASTString extends SimpleNode {
  public ASTString(int id) {
    super(id);
  }

  public ASTString(RPLParser p, int id) {
    super(p, id);
  }

  public RPLObject getValue() {
    return new RPLStringValue((String)info);
  }
}
