/* Generated By:JJTree: Do not edit this line. ASTTrue.java */

package uchicago.src.sim.parameter.rpl;

public class ASTTrue extends SimpleNode {
  public ASTTrue(int id) {
    super(id);
  }

  public ASTTrue(RPLParser p, int id) {
    super(p, id);
  }

  public RPLObject getValue() {
    return new RPLBooleanValue(true);
  }

}
