/* Generated By:JJTree: Do not edit this line. RPLParserTreeConstants.java */

package uchicago.src.sim.parameter.rpl;

public interface RPLParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVOID = 1;
  public int JJTPARAM_ASSIGN = 2;
  public int JJTLIST_ASSIGN = 3;
  public int JJTCONST_ASSIGN = 4;
  public int JJTLIST = 5;
  public int JJTTRUE = 6;
  public int JJTFALSE = 7;
  public int JJTDOTTED_NAME = 8;
  public int JJTBLOCKDEF = 9;
  public int JJTCONSTANT = 10;
  public int JJTSUBBLOCK = 11;
  public int JJTSUITE = 12;
  public int JJTPARAMETER = 13;
  public int JJTNAME = 14;
  public int JJTINT = 15;
  public int JJTFLOAT = 16;
  public int JJTSTRING = 17;


  public String[] jjtNodeName = {
    "compilationUnit",
    "void",
    "param_assign",
    "list_assign",
    "const_assign",
    "list",
    "True",
    "False",
    "dotted_name",
    "blockdef",
    "Constant",
    "subBlock",
    "suite",
    "Parameter",
    "Name",
    "Int",
    "Float",
    "String",
  };
}
